"""MCP tools for NotebookLM note (memo) management.

This module provides four MCP tools for note operations:

- ``notebooklm_create_note``: Create a new plain text note.
- ``notebooklm_list_notes``: List all notes in a notebook.
- ``notebooklm_get_note``: Get the full content of a specific note.
- ``notebooklm_delete_note``: Delete a note from a notebook.

Each tool retrieves the ``NotebookLMBrowserManager`` from the lifespan
context via ``ctx.lifespan_context["browser_manager"]`` and instantiates
a ``NoteService`` for the operation.

See Also
--------
notebooklm.services.note : NoteService implementation.
notebooklm.mcp.server : Server setup with lifespan.
"""

from __future__ import annotations

from typing import Any

from fastmcp import Context
from mcp.server.fastmcp import FastMCP

from notebooklm.decorators import mcp_tool_handler
from notebooklm.services.note import NoteService


def register_note_tools(mcp: FastMCP) -> None:
    """Register note management MCP tools on the server.

    Parameters
    ----------
    mcp : FastMCP
        The FastMCP server instance to register tools on.
    """

    @mcp.tool()
    @mcp_tool_handler("notebooklm_create_note")
    async def notebooklm_create_note(
        notebook_id: str,
        content: str,
        ctx: Context,
        title: str | None = None,
    ) -> dict[str, Any]:
        """Create a new plain text note in a NotebookLM notebook.

        Navigates to the notebook page, clicks the "Add note" button,
        fills in the optional title and content, then returns the
        created note's metadata.

        Parameters
        ----------
        notebook_id : str
            UUID of the target notebook. Must not be empty.
        content : str
            Text content for the note. Must not be empty.
        ctx : Context
            MCP context providing access to lifespan resources.
        title : str | None
            Optional display title for the note.
            If None, the note title is auto-generated by NotebookLM.

        Returns
        -------
        dict
            JSON object containing:
            - note_id: Identifier for the created note.
            - title: Display title of the note.
        """
        browser_manager = ctx.lifespan_context["browser_manager"]
        service = NoteService(browser_manager)
        note = await service.create_note(
            notebook_id,
            content,
            title=title,
        )
        return note.model_dump()

    @mcp.tool()
    @mcp_tool_handler("notebooklm_list_notes")
    async def notebooklm_list_notes(
        notebook_id: str,
        ctx: Context,
    ) -> dict[str, Any]:
        """List all notes in a NotebookLM notebook.

        Navigates to the notebook page and scrapes the notes panel
        to extract metadata for each note.

        Parameters
        ----------
        notebook_id : str
            UUID of the target notebook. Must not be empty.
        ctx : Context
            MCP context providing access to lifespan resources.

        Returns
        -------
        dict
            JSON object containing:
            - notes: List of note objects with note_id and title.
            - total: Total number of notes found.
        """
        browser_manager = ctx.lifespan_context["browser_manager"]
        service = NoteService(browser_manager)
        notes = await service.list_notes(notebook_id)
        return {
            "notes": [note.model_dump() for note in notes],
            "total": len(notes),
        }

    @mcp.tool()
    @mcp_tool_handler("notebooklm_get_note")
    async def notebooklm_get_note(
        notebook_id: str,
        note_index: int,
        ctx: Context,
    ) -> dict[str, Any]:
        """Get the full content of a specific note in a NotebookLM notebook.

        Navigates to the notebook page, clicks on the note at the
        given index to open it, and extracts the title and content.

        Parameters
        ----------
        notebook_id : str
            UUID of the target notebook. Must not be empty.
        note_index : int
            Zero-based index of the note in the notes list.
            Must be non-negative.
        ctx : Context
            MCP context providing access to lifespan resources.

        Returns
        -------
        dict
            JSON object containing:
            - note_id: Identifier for the note.
            - title: Display title of the note.
            - content: Full text content of the note.
        """
        browser_manager = ctx.lifespan_context["browser_manager"]
        service = NoteService(browser_manager)
        note = await service.get_note(notebook_id, note_index)
        return note.model_dump()

    @mcp.tool()
    @mcp_tool_handler("notebooklm_delete_note")
    async def notebooklm_delete_note(
        notebook_id: str,
        note_index: int,
        ctx: Context,
    ) -> dict[str, Any]:
        """Delete a note from a NotebookLM notebook.

        Navigates to the notebook page, locates the note at the given
        index, clicks the delete button, and confirms deletion.

        Parameters
        ----------
        notebook_id : str
            UUID of the target notebook. Must not be empty.
        note_index : int
            Zero-based index of the note to delete.
            Must be non-negative.
        ctx : Context
            MCP context providing access to lifespan resources.

        Returns
        -------
        dict
            JSON object containing:
            - notebook_id: UUID of the notebook.
            - note_index: Index of the deleted note.
            - deleted: Whether the note was deleted successfully.
        """
        browser_manager = ctx.lifespan_context["browser_manager"]
        service = NoteService(browser_manager)
        deleted = await service.delete_note(notebook_id, note_index)
        return {
            "notebook_id": notebook_id,
            "note_index": note_index,
            "deleted": deleted,
        }
